/*
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.ide;

import br.ufscar.dc.compiladores.PlayLangRuntimeModule;
import br.ufscar.dc.compiladores.PlayLangStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PlayLangIdeSetup extends PlayLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PlayLangRuntimeModule(), new PlayLangIdeModule()));
	}
	
}
