/*
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPlayLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.ufscar.dc.compiladores.playLang.PlayLangPackage.eINSTANCE);
		return result;
	}
}
