/*
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlayLangRuntimeModule extends AbstractPlayLangRuntimeModule {
}
