/*
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.ui.tests;

import br.ufscar.dc.compiladores.playlang.ui.internal.PlaylangActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PlayLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PlaylangActivator.getInstance().getInjector("br.ufscar.dc.compiladores.PlayLang");
	}

}
