/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang.impl;

import br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica;
import br.ufscar.dc.compiladores.playLang.ExpressaoRelacional;
import br.ufscar.dc.compiladores.playLang.PlayLangPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expressao Relacional</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.impl.ExpressaoRelacionalImpl#getExpressoes <em>Expressoes</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.impl.ExpressaoRelacionalImpl#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExpressaoRelacionalImpl extends MinimalEObjectImpl.Container implements ExpressaoRelacional
{
  /**
   * The cached value of the '{@link #getExpressoes() <em>Expressoes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpressoes()
   * @generated
   * @ordered
   */
  protected EList<ExpressaoAritmetica> expressoes;

  /**
   * The cached value of the '{@link #getOp() <em>Op</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOp()
   * @generated
   * @ordered
   */
  protected EList<String> op;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpressaoRelacionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PlayLangPackage.Literals.EXPRESSAO_RELACIONAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ExpressaoAritmetica> getExpressoes()
  {
    if (expressoes == null)
    {
      expressoes = new EObjectContainmentEList<ExpressaoAritmetica>(ExpressaoAritmetica.class, this, PlayLangPackage.EXPRESSAO_RELACIONAL__EXPRESSOES);
    }
    return expressoes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getOp()
  {
    if (op == null)
    {
      op = new EDataTypeEList<String>(String.class, this, PlayLangPackage.EXPRESSAO_RELACIONAL__OP);
    }
    return op;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PlayLangPackage.EXPRESSAO_RELACIONAL__EXPRESSOES:
        return ((InternalEList<?>)getExpressoes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PlayLangPackage.EXPRESSAO_RELACIONAL__EXPRESSOES:
        return getExpressoes();
      case PlayLangPackage.EXPRESSAO_RELACIONAL__OP:
        return getOp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PlayLangPackage.EXPRESSAO_RELACIONAL__EXPRESSOES:
        getExpressoes().clear();
        getExpressoes().addAll((Collection<? extends ExpressaoAritmetica>)newValue);
        return;
      case PlayLangPackage.EXPRESSAO_RELACIONAL__OP:
        getOp().clear();
        getOp().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PlayLangPackage.EXPRESSAO_RELACIONAL__EXPRESSOES:
        getExpressoes().clear();
        return;
      case PlayLangPackage.EXPRESSAO_RELACIONAL__OP:
        getOp().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PlayLangPackage.EXPRESSAO_RELACIONAL__EXPRESSOES:
        return expressoes != null && !expressoes.isEmpty();
      case PlayLangPackage.EXPRESSAO_RELACIONAL__OP:
        return op != null && !op.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (op: ");
    result.append(op);
    result.append(')');
    return result.toString();
  }

} //ExpressaoRelacionalImpl
