/*
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class PlayLangProposalProvider extends AbstractPlayLangProposalProvider {
}
