/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atribuicao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Atribuicao#getExpressao <em>Expressao</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Atribuicao#getString <em>String</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getAtribuicao()
 * @model
 * @generated
 */
public interface Atribuicao extends Comando
{
  /**
   * Returns the value of the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressao</em>' containment reference.
   * @see #setExpressao(Expressao)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getAtribuicao_Expressao()
   * @model containment="true"
   * @generated
   */
  Expressao getExpressao();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Atribuicao#getExpressao <em>Expressao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expressao</em>' containment reference.
   * @see #getExpressao()
   * @generated
   */
  void setExpressao(Expressao value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getAtribuicao_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Atribuicao#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

} // Atribuicao
