/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Escolha</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Escolha#getTextos <em>Textos</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Escolha#getComando <em>Comando</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Escolha#getIf <em>If</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Escolha#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getEscolha()
 * @model
 * @generated
 */
public interface Escolha extends EObject
{
  /**
   * Returns the value of the '<em><b>Textos</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.playLang.Texto}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Textos</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getEscolha_Textos()
   * @model containment="true"
   * @generated
   */
  EList<Texto> getTextos();

  /**
   * Returns the value of the '<em><b>Comando</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.playLang.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comando</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getEscolha_Comando()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComando();

  /**
   * Returns the value of the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>If</em>' containment reference.
   * @see #setIf(If)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getEscolha_If()
   * @model containment="true"
   * @generated
   */
  If getIf();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Escolha#getIf <em>If</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If</em>' containment reference.
   * @see #getIf()
   * @generated
   */
  void setIf(If value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' reference.
   * @see #setId(Cena)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getEscolha_Id()
   * @model
   * @generated
   */
  Cena getId();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Escolha#getId <em>Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' reference.
   * @see #getId()
   * @generated
   */
  void setId(Cena value);

} // Escolha
