/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Expressao#getTermos <em>Termos</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Expressao#getOu <em>Ou</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getExpressao()
 * @model
 * @generated
 */
public interface Expressao extends EObject
{
  /**
   * Returns the value of the '<em><b>Termos</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.playLang.TermoLogico}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termos</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getExpressao_Termos()
   * @model containment="true"
   * @generated
   */
  EList<TermoLogico> getTermos();

  /**
   * Returns the value of the '<em><b>Ou</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ou</em>' attribute list.
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getExpressao_Ou()
   * @model unique="false"
   * @generated
   */
  EList<String> getOu();

} // Expressao
