/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao Aritmetica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica#getTermos <em>Termos</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getExpressaoAritmetica()
 * @model
 * @generated
 */
public interface ExpressaoAritmetica extends EObject
{
  /**
   * Returns the value of the '<em><b>Termos</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.playLang.Termo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termos</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getExpressaoAritmetica_Termos()
   * @model containment="true"
   * @generated
   */
  EList<Termo> getTermos();

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getExpressaoAritmetica_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

} // ExpressaoAritmetica
