/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Fator#getParcelas <em>Parcelas</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Fator#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getFator()
 * @model
 * @generated
 */
public interface Fator extends EObject
{
  /**
   * Returns the value of the '<em><b>Parcelas</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.playLang.Parcela}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parcelas</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getFator_Parcelas()
   * @model containment="true"
   * @generated
   */
  EList<Parcela> getParcelas();

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute list.
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getFator_Op()
   * @model unique="false"
   * @generated
   */
  EList<String> getOp();

} // Fator
