/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Imagem</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Imagem#getCaminho <em>Caminho</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Imagem#getLinha <em>Linha</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Imagem#getColuna <em>Coluna</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getImagem()
 * @model
 * @generated
 */
public interface Imagem extends EObject
{
  /**
   * Returns the value of the '<em><b>Caminho</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Caminho</em>' attribute.
   * @see #setCaminho(String)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getImagem_Caminho()
   * @model
   * @generated
   */
  String getCaminho();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Imagem#getCaminho <em>Caminho</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Caminho</em>' attribute.
   * @see #getCaminho()
   * @generated
   */
  void setCaminho(String value);

  /**
   * Returns the value of the '<em><b>Linha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Linha</em>' attribute.
   * @see #setLinha(int)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getImagem_Linha()
   * @model
   * @generated
   */
  int getLinha();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Imagem#getLinha <em>Linha</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Linha</em>' attribute.
   * @see #getLinha()
   * @generated
   */
  void setLinha(int value);

  /**
   * Returns the value of the '<em><b>Coluna</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coluna</em>' attribute.
   * @see #setColuna(int)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getImagem_Coluna()
   * @model
   * @generated
   */
  int getColuna();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Imagem#getColuna <em>Coluna</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coluna</em>' attribute.
   * @see #getColuna()
   * @generated
   */
  void setColuna(int value);

} // Imagem
