/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parcela logica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Parcela_logica#getP <em>P</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Parcela_logica#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getParcela_logica()
 * @model
 * @generated
 */
public interface Parcela_logica extends EObject
{
  /**
   * Returns the value of the '<em><b>P</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' attribute.
   * @see #setP(String)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getParcela_logica_P()
   * @model
   * @generated
   */
  String getP();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Parcela_logica#getP <em>P</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P</em>' attribute.
   * @see #getP()
   * @generated
   */
  void setP(String value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(ExpressaoRelacional)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getParcela_logica_Exp()
   * @model containment="true"
   * @generated
   */
  ExpressaoRelacional getExp();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Parcela_logica#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(ExpressaoRelacional value);

} // Parcela_logica
