/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parcela</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Parcela#isSub <em>Sub</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Parcela#getId <em>Id</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Parcela#getInt <em>Int</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getParcela()
 * @model
 * @generated
 */
public interface Parcela extends EObject
{
  /**
   * Returns the value of the '<em><b>Sub</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub</em>' attribute.
   * @see #setSub(boolean)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getParcela_Sub()
   * @model
   * @generated
   */
  boolean isSub();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Parcela#isSub <em>Sub</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub</em>' attribute.
   * @see #isSub()
   * @generated
   */
  void setSub(boolean value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' reference.
   * @see #setId(Declaracao)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getParcela_Id()
   * @model
   * @generated
   */
  Declaracao getId();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Parcela#getId <em>Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' reference.
   * @see #getId()
   * @generated
   */
  void setId(Declaracao value);

  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getParcela_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Parcela#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

} // Parcela
