/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Play Sound</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.PlaySound#getFile_path <em>File path</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getPlaySound()
 * @model
 * @generated
 */
public interface PlaySound extends EObject
{
  /**
   * Returns the value of the '<em><b>File path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File path</em>' attribute.
   * @see #setFile_path(String)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getPlaySound_File_path()
   * @model
   * @generated
   */
  String getFile_path();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.PlaySound#getFile_path <em>File path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File path</em>' attribute.
   * @see #getFile_path()
   * @generated
   */
  void setFile_path(String value);

} // PlaySound
