/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.ufscar.dc.compiladores.playLang.PlayLangFactory
 * @model kind="package"
 * @generated
 */
public interface PlayLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "playLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ufscar.br/dc/compiladores/PlayLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "playLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PlayLangPackage eINSTANCE = br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl.init();

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.GameImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Linha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__LINHA = 0;

  /**
   * The feature id for the '<em><b>Coluna</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__COLUNA = 1;

  /**
   * The feature id for the '<em><b>Declaracoes globais</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__DECLARACOES_GLOBAIS = 2;

  /**
   * The feature id for the '<em><b>Evento</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__EVENTO = 3;

  /**
   * The feature id for the '<em><b>Cenas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__CENAS = 4;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.EventoGlobalImpl <em>Evento Global</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.EventoGlobalImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getEventoGlobal()
   * @generated
   */
  int EVENTO_GLOBAL = 1;

  /**
   * The feature id for the '<em><b>Comandos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENTO_GLOBAL__COMANDOS = 0;

  /**
   * The number of structural features of the '<em>Evento Global</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENTO_GLOBAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.DeclaracaoImpl <em>Declaracao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.DeclaracaoImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getDeclaracao()
   * @generated
   */
  int DECLARACAO = 2;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__TIPO = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__NAME = 1;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__STRING = 2;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__BOOL = 3;

  /**
   * The feature id for the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__INT = 4;

  /**
   * The feature id for the '<em><b>Zero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__ZERO = 5;

  /**
   * The number of structural features of the '<em>Declaracao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.CenaImpl <em>Cena</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.CenaImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getCena()
   * @generated
   */
  int CENA = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENA__NAME = 0;

  /**
   * The feature id for the '<em><b>Textos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENA__TEXTOS = 1;

  /**
   * The feature id for the '<em><b>Imagem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENA__IMAGEM = 2;

  /**
   * The feature id for the '<em><b>Sound</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENA__SOUND = 3;

  /**
   * The feature id for the '<em><b>Escolhas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENA__ESCOLHAS = 4;

  /**
   * The number of structural features of the '<em>Cena</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CENA_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.ImagemImpl <em>Imagem</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.ImagemImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getImagem()
   * @generated
   */
  int IMAGEM = 4;

  /**
   * The feature id for the '<em><b>Caminho</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGEM__CAMINHO = 0;

  /**
   * The feature id for the '<em><b>Linha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGEM__LINHA = 1;

  /**
   * The feature id for the '<em><b>Coluna</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGEM__COLUNA = 2;

  /**
   * The number of structural features of the '<em>Imagem</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGEM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.TextoImpl <em>Texto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.TextoImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getTexto()
   * @generated
   */
  int TEXTO = 5;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTO__TEXT = 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTO__VAR = 1;

  /**
   * The number of structural features of the '<em>Texto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXTO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.EscolhasImpl <em>Escolhas</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.EscolhasImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getEscolhas()
   * @generated
   */
  int ESCOLHAS = 6;

  /**
   * The feature id for the '<em><b>Single Choice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHAS__SINGLE_CHOICE = 0;

  /**
   * The feature id for the '<em><b>Has If</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHAS__HAS_IF = 1;

  /**
   * The feature id for the '<em><b>Expressao If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHAS__EXPRESSAO_IF = 2;

  /**
   * The feature id for the '<em><b>Escolhas IF</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHAS__ESCOLHAS_IF = 3;

  /**
   * The feature id for the '<em><b>Has Else</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHAS__HAS_ELSE = 4;

  /**
   * The feature id for the '<em><b>Escolhas ELSE</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHAS__ESCOLHAS_ELSE = 5;

  /**
   * The number of structural features of the '<em>Escolhas</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHAS_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.EscolhaImpl <em>Escolha</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.EscolhaImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getEscolha()
   * @generated
   */
  int ESCOLHA = 7;

  /**
   * The feature id for the '<em><b>Textos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHA__TEXTOS = 0;

  /**
   * The feature id for the '<em><b>Comando</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHA__COMANDO = 1;

  /**
   * The feature id for the '<em><b>If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHA__IF = 2;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHA__ID = 3;

  /**
   * The number of structural features of the '<em>Escolha</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESCOLHA_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.ComandoImpl <em>Comando</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.ComandoImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getComando()
   * @generated
   */
  int COMANDO = 8;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO__ID = 0;

  /**
   * The number of structural features of the '<em>Comando</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.RandomImpl <em>Random</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.RandomImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getRandom()
   * @generated
   */
  int RANDOM = 9;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM__ID = COMANDO__ID;

  /**
   * The feature id for the '<em><b>Possibilidades Int</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM__POSSIBILIDADES_INT = COMANDO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Possibilidades String</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM__POSSIBILIDADES_STRING = COMANDO_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Possibilidades Bool</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM__POSSIBILIDADES_BOOL = COMANDO_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Random</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.PlaySoundImpl <em>Play Sound</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.PlaySoundImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getPlaySound()
   * @generated
   */
  int PLAY_SOUND = 10;

  /**
   * The feature id for the '<em><b>File path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAY_SOUND__FILE_PATH = 0;

  /**
   * The number of structural features of the '<em>Play Sound</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAY_SOUND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.IfImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getIf()
   * @generated
   */
  int IF = 11;

  /**
   * The feature id for the '<em><b>Expressao If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__EXPRESSAO_IF = 0;

  /**
   * The feature id for the '<em><b>Id If</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ID_IF = 1;

  /**
   * The feature id for the '<em><b>Elif</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ELIF = 2;

  /**
   * The feature id for the '<em><b>Id Else</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ID_ELSE = 3;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.AtribuicaoImpl <em>Atribuicao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.AtribuicaoImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getAtribuicao()
   * @generated
   */
  int ATRIBUICAO = 12;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUICAO__ID = COMANDO__ID;

  /**
   * The feature id for the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUICAO__EXPRESSAO = COMANDO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUICAO__STRING = COMANDO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Atribuicao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUICAO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.ExpressaoImpl <em>Expressao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.ExpressaoImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getExpressao()
   * @generated
   */
  int EXPRESSAO = 13;

  /**
   * The feature id for the '<em><b>Termos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO__TERMOS = 0;

  /**
   * The feature id for the '<em><b>Ou</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO__OU = 1;

  /**
   * The number of structural features of the '<em>Expressao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.TermoLogicoImpl <em>Termo Logico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.TermoLogicoImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getTermoLogico()
   * @generated
   */
  int TERMO_LOGICO = 14;

  /**
   * The feature id for the '<em><b>Fatores</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_LOGICO__FATORES = 0;

  /**
   * The feature id for the '<em><b>E</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_LOGICO__E = 1;

  /**
   * The number of structural features of the '<em>Termo Logico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_LOGICO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.FatorLogicoImpl <em>Fator Logico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.FatorLogicoImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getFatorLogico()
   * @generated
   */
  int FATOR_LOGICO = 15;

  /**
   * The feature id for the '<em><b>Nao</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_LOGICO__NAO = 0;

  /**
   * The feature id for the '<em><b>Parcela</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_LOGICO__PARCELA = 1;

  /**
   * The number of structural features of the '<em>Fator Logico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_LOGICO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.Parcela_logicaImpl <em>Parcela logica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.Parcela_logicaImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getParcela_logica()
   * @generated
   */
  int PARCELA_LOGICA = 16;

  /**
   * The feature id for the '<em><b>P</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARCELA_LOGICA__P = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARCELA_LOGICA__EXP = 1;

  /**
   * The number of structural features of the '<em>Parcela logica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARCELA_LOGICA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.ExpressaoRelacionalImpl <em>Expressao Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.ExpressaoRelacionalImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getExpressaoRelacional()
   * @generated
   */
  int EXPRESSAO_RELACIONAL = 17;

  /**
   * The feature id for the '<em><b>Expressoes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL__EXPRESSOES = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL__OP = 1;

  /**
   * The number of structural features of the '<em>Expressao Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.ExpressaoAritmeticaImpl <em>Expressao Aritmetica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.ExpressaoAritmeticaImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getExpressaoAritmetica()
   * @generated
   */
  int EXPRESSAO_ARITMETICA = 18;

  /**
   * The feature id for the '<em><b>Termos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA__TERMOS = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA__OP = 1;

  /**
   * The number of structural features of the '<em>Expressao Aritmetica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.TermoImpl <em>Termo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.TermoImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getTermo()
   * @generated
   */
  int TERMO = 19;

  /**
   * The feature id for the '<em><b>Fatores</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO__FATORES = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO__OP = 1;

  /**
   * The number of structural features of the '<em>Termo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.FatorImpl <em>Fator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.FatorImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getFator()
   * @generated
   */
  int FATOR = 20;

  /**
   * The feature id for the '<em><b>Parcelas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR__PARCELAS = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR__OP = 1;

  /**
   * The number of structural features of the '<em>Fator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.playLang.impl.ParcelaImpl <em>Parcela</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.playLang.impl.ParcelaImpl
   * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getParcela()
   * @generated
   */
  int PARCELA = 21;

  /**
   * The feature id for the '<em><b>Sub</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARCELA__SUB = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARCELA__ID = 1;

  /**
   * The feature id for the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARCELA__INT = 2;

  /**
   * The number of structural features of the '<em>Parcela</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARCELA_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Game#getLinha <em>Linha</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Linha</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Game#getLinha()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Linha();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Game#getColuna <em>Coluna</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Coluna</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Game#getColuna()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Coluna();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Game#getDeclaracoes_globais <em>Declaracoes globais</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declaracoes globais</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Game#getDeclaracoes_globais()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Declaracoes_globais();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.Game#getEvento <em>Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Evento</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Game#getEvento()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Evento();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Game#getCenas <em>Cenas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cenas</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Game#getCenas()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Cenas();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.EventoGlobal <em>Evento Global</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evento Global</em>'.
   * @see br.ufscar.dc.compiladores.playLang.EventoGlobal
   * @generated
   */
  EClass getEventoGlobal();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.EventoGlobal#getComandos <em>Comandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comandos</em>'.
   * @see br.ufscar.dc.compiladores.playLang.EventoGlobal#getComandos()
   * @see #getEventoGlobal()
   * @generated
   */
  EReference getEventoGlobal_Comandos();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Declaracao <em>Declaracao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaracao</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Declaracao
   * @generated
   */
  EClass getDeclaracao();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Declaracao#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Declaracao#getTipo()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Tipo();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Declaracao#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Declaracao#getName()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Name();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Declaracao#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Declaracao#getString()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_String();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Declaracao#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Declaracao#getBool()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Bool();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Declaracao#getInt <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Declaracao#getInt()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Int();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Declaracao#getZero <em>Zero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Zero</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Declaracao#getZero()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Zero();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Cena <em>Cena</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cena</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Cena
   * @generated
   */
  EClass getCena();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Cena#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Cena#getName()
   * @see #getCena()
   * @generated
   */
  EAttribute getCena_Name();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Cena#getTextos <em>Textos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Textos</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Cena#getTextos()
   * @see #getCena()
   * @generated
   */
  EReference getCena_Textos();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.Cena#getImagem <em>Imagem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Imagem</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Cena#getImagem()
   * @see #getCena()
   * @generated
   */
  EReference getCena_Imagem();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.Cena#getSound <em>Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sound</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Cena#getSound()
   * @see #getCena()
   * @generated
   */
  EReference getCena_Sound();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Cena#getEscolhas <em>Escolhas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Escolhas</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Cena#getEscolhas()
   * @see #getCena()
   * @generated
   */
  EReference getCena_Escolhas();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Imagem <em>Imagem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Imagem</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Imagem
   * @generated
   */
  EClass getImagem();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Imagem#getCaminho <em>Caminho</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Caminho</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Imagem#getCaminho()
   * @see #getImagem()
   * @generated
   */
  EAttribute getImagem_Caminho();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Imagem#getLinha <em>Linha</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Linha</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Imagem#getLinha()
   * @see #getImagem()
   * @generated
   */
  EAttribute getImagem_Linha();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Imagem#getColuna <em>Coluna</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Coluna</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Imagem#getColuna()
   * @see #getImagem()
   * @generated
   */
  EAttribute getImagem_Coluna();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Texto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Texto</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Texto
   * @generated
   */
  EClass getTexto();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Texto#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Texto#getText()
   * @see #getTexto()
   * @generated
   */
  EAttribute getTexto_Text();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.playLang.Texto#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Texto#getVar()
   * @see #getTexto()
   * @generated
   */
  EReference getTexto_Var();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Escolhas <em>Escolhas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Escolhas</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolhas
   * @generated
   */
  EClass getEscolhas();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.Escolhas#getSingleChoice <em>Single Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Single Choice</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolhas#getSingleChoice()
   * @see #getEscolhas()
   * @generated
   */
  EReference getEscolhas_SingleChoice();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Escolhas#isHasIf <em>Has If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has If</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolhas#isHasIf()
   * @see #getEscolhas()
   * @generated
   */
  EAttribute getEscolhas_HasIf();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.Escolhas#getExpressaoIf <em>Expressao If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao If</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolhas#getExpressaoIf()
   * @see #getEscolhas()
   * @generated
   */
  EReference getEscolhas_ExpressaoIf();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Escolhas#getEscolhasIF <em>Escolhas IF</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Escolhas IF</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolhas#getEscolhasIF()
   * @see #getEscolhas()
   * @generated
   */
  EReference getEscolhas_EscolhasIF();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Escolhas#isHasElse <em>Has Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has Else</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolhas#isHasElse()
   * @see #getEscolhas()
   * @generated
   */
  EAttribute getEscolhas_HasElse();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Escolhas#getEscolhasELSE <em>Escolhas ELSE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Escolhas ELSE</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolhas#getEscolhasELSE()
   * @see #getEscolhas()
   * @generated
   */
  EReference getEscolhas_EscolhasELSE();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Escolha <em>Escolha</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Escolha</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolha
   * @generated
   */
  EClass getEscolha();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Escolha#getTextos <em>Textos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Textos</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolha#getTextos()
   * @see #getEscolha()
   * @generated
   */
  EReference getEscolha_Textos();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Escolha#getComando <em>Comando</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comando</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolha#getComando()
   * @see #getEscolha()
   * @generated
   */
  EReference getEscolha_Comando();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.Escolha#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolha#getIf()
   * @see #getEscolha()
   * @generated
   */
  EReference getEscolha_If();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.playLang.Escolha#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Escolha#getId()
   * @see #getEscolha()
   * @generated
   */
  EReference getEscolha_Id();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Comando <em>Comando</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Comando
   * @generated
   */
  EClass getComando();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.playLang.Comando#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Comando#getId()
   * @see #getComando()
   * @generated
   */
  EReference getComando_Id();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Random <em>Random</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Random</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Random
   * @generated
   */
  EClass getRandom();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.Random#getPossibilidadesInt <em>Possibilidades Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Possibilidades Int</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Random#getPossibilidadesInt()
   * @see #getRandom()
   * @generated
   */
  EAttribute getRandom_PossibilidadesInt();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.Random#getPossibilidadesString <em>Possibilidades String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Possibilidades String</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Random#getPossibilidadesString()
   * @see #getRandom()
   * @generated
   */
  EAttribute getRandom_PossibilidadesString();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.Random#getPossibilidadesBool <em>Possibilidades Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Possibilidades Bool</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Random#getPossibilidadesBool()
   * @see #getRandom()
   * @generated
   */
  EAttribute getRandom_PossibilidadesBool();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.PlaySound <em>Play Sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Play Sound</em>'.
   * @see br.ufscar.dc.compiladores.playLang.PlaySound
   * @generated
   */
  EClass getPlaySound();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.PlaySound#getFile_path <em>File path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File path</em>'.
   * @see br.ufscar.dc.compiladores.playLang.PlaySound#getFile_path()
   * @see #getPlaySound()
   * @generated
   */
  EAttribute getPlaySound_File_path();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see br.ufscar.dc.compiladores.playLang.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.If#getExpressaoIf <em>Expressao If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao If</em>'.
   * @see br.ufscar.dc.compiladores.playLang.If#getExpressaoIf()
   * @see #getIf()
   * @generated
   */
  EReference getIf_ExpressaoIf();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.playLang.If#getIdIf <em>Id If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id If</em>'.
   * @see br.ufscar.dc.compiladores.playLang.If#getIdIf()
   * @see #getIf()
   * @generated
   */
  EReference getIf_IdIf();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.If#getElif <em>Elif</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elif</em>'.
   * @see br.ufscar.dc.compiladores.playLang.If#getElif()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Elif();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.playLang.If#getIdElse <em>Id Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id Else</em>'.
   * @see br.ufscar.dc.compiladores.playLang.If#getIdElse()
   * @see #getIf()
   * @generated
   */
  EReference getIf_IdElse();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Atribuicao <em>Atribuicao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atribuicao</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Atribuicao
   * @generated
   */
  EClass getAtribuicao();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.Atribuicao#getExpressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Atribuicao#getExpressao()
   * @see #getAtribuicao()
   * @generated
   */
  EReference getAtribuicao_Expressao();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Atribuicao#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Atribuicao#getString()
   * @see #getAtribuicao()
   * @generated
   */
  EAttribute getAtribuicao_String();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Expressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Expressao
   * @generated
   */
  EClass getExpressao();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Expressao#getTermos <em>Termos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Termos</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Expressao#getTermos()
   * @see #getExpressao()
   * @generated
   */
  EReference getExpressao_Termos();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.Expressao#getOu <em>Ou</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ou</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Expressao#getOu()
   * @see #getExpressao()
   * @generated
   */
  EAttribute getExpressao_Ou();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.TermoLogico <em>Termo Logico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Logico</em>'.
   * @see br.ufscar.dc.compiladores.playLang.TermoLogico
   * @generated
   */
  EClass getTermoLogico();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.TermoLogico#getFatores <em>Fatores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fatores</em>'.
   * @see br.ufscar.dc.compiladores.playLang.TermoLogico#getFatores()
   * @see #getTermoLogico()
   * @generated
   */
  EReference getTermoLogico_Fatores();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.TermoLogico#getE <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>E</em>'.
   * @see br.ufscar.dc.compiladores.playLang.TermoLogico#getE()
   * @see #getTermoLogico()
   * @generated
   */
  EAttribute getTermoLogico_E();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.FatorLogico <em>Fator Logico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Logico</em>'.
   * @see br.ufscar.dc.compiladores.playLang.FatorLogico
   * @generated
   */
  EClass getFatorLogico();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.FatorLogico#isNao <em>Nao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nao</em>'.
   * @see br.ufscar.dc.compiladores.playLang.FatorLogico#isNao()
   * @see #getFatorLogico()
   * @generated
   */
  EAttribute getFatorLogico_Nao();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.FatorLogico#getParcela <em>Parcela</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parcela</em>'.
   * @see br.ufscar.dc.compiladores.playLang.FatorLogico#getParcela()
   * @see #getFatorLogico()
   * @generated
   */
  EReference getFatorLogico_Parcela();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Parcela_logica <em>Parcela logica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parcela logica</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Parcela_logica
   * @generated
   */
  EClass getParcela_logica();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Parcela_logica#getP <em>P</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>P</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Parcela_logica#getP()
   * @see #getParcela_logica()
   * @generated
   */
  EAttribute getParcela_logica_P();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.playLang.Parcela_logica#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Parcela_logica#getExp()
   * @see #getParcela_logica()
   * @generated
   */
  EReference getParcela_logica_Exp();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.ExpressaoRelacional <em>Expressao Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao Relacional</em>'.
   * @see br.ufscar.dc.compiladores.playLang.ExpressaoRelacional
   * @generated
   */
  EClass getExpressaoRelacional();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.ExpressaoRelacional#getExpressoes <em>Expressoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressoes</em>'.
   * @see br.ufscar.dc.compiladores.playLang.ExpressaoRelacional#getExpressoes()
   * @see #getExpressaoRelacional()
   * @generated
   */
  EReference getExpressaoRelacional_Expressoes();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.ExpressaoRelacional#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Op</em>'.
   * @see br.ufscar.dc.compiladores.playLang.ExpressaoRelacional#getOp()
   * @see #getExpressaoRelacional()
   * @generated
   */
  EAttribute getExpressaoRelacional_Op();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica <em>Expressao Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao Aritmetica</em>'.
   * @see br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica
   * @generated
   */
  EClass getExpressaoAritmetica();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica#getTermos <em>Termos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Termos</em>'.
   * @see br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica#getTermos()
   * @see #getExpressaoAritmetica()
   * @generated
   */
  EReference getExpressaoAritmetica_Termos();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Op</em>'.
   * @see br.ufscar.dc.compiladores.playLang.ExpressaoAritmetica#getOp()
   * @see #getExpressaoAritmetica()
   * @generated
   */
  EAttribute getExpressaoAritmetica_Op();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Termo <em>Termo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Termo
   * @generated
   */
  EClass getTermo();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Termo#getFatores <em>Fatores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fatores</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Termo#getFatores()
   * @see #getTermo()
   * @generated
   */
  EReference getTermo_Fatores();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.Termo#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Op</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Termo#getOp()
   * @see #getTermo()
   * @generated
   */
  EAttribute getTermo_Op();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Fator <em>Fator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Fator
   * @generated
   */
  EClass getFator();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.playLang.Fator#getParcelas <em>Parcelas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parcelas</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Fator#getParcelas()
   * @see #getFator()
   * @generated
   */
  EReference getFator_Parcelas();

  /**
   * Returns the meta object for the attribute list '{@link br.ufscar.dc.compiladores.playLang.Fator#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Op</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Fator#getOp()
   * @see #getFator()
   * @generated
   */
  EAttribute getFator_Op();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.playLang.Parcela <em>Parcela</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parcela</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Parcela
   * @generated
   */
  EClass getParcela();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Parcela#isSub <em>Sub</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sub</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Parcela#isSub()
   * @see #getParcela()
   * @generated
   */
  EAttribute getParcela_Sub();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.playLang.Parcela#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Id</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Parcela#getId()
   * @see #getParcela()
   * @generated
   */
  EReference getParcela_Id();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.playLang.Parcela#getInt <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int</em>'.
   * @see br.ufscar.dc.compiladores.playLang.Parcela#getInt()
   * @see #getParcela()
   * @generated
   */
  EAttribute getParcela_Int();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PlayLangFactory getPlayLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.GameImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Linha</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__LINHA = eINSTANCE.getGame_Linha();

    /**
     * The meta object literal for the '<em><b>Coluna</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__COLUNA = eINSTANCE.getGame_Coluna();

    /**
     * The meta object literal for the '<em><b>Declaracoes globais</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__DECLARACOES_GLOBAIS = eINSTANCE.getGame_Declaracoes_globais();

    /**
     * The meta object literal for the '<em><b>Evento</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__EVENTO = eINSTANCE.getGame_Evento();

    /**
     * The meta object literal for the '<em><b>Cenas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__CENAS = eINSTANCE.getGame_Cenas();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.EventoGlobalImpl <em>Evento Global</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.EventoGlobalImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getEventoGlobal()
     * @generated
     */
    EClass EVENTO_GLOBAL = eINSTANCE.getEventoGlobal();

    /**
     * The meta object literal for the '<em><b>Comandos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENTO_GLOBAL__COMANDOS = eINSTANCE.getEventoGlobal_Comandos();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.DeclaracaoImpl <em>Declaracao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.DeclaracaoImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getDeclaracao()
     * @generated
     */
    EClass DECLARACAO = eINSTANCE.getDeclaracao();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__TIPO = eINSTANCE.getDeclaracao_Tipo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__NAME = eINSTANCE.getDeclaracao_Name();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__STRING = eINSTANCE.getDeclaracao_String();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__BOOL = eINSTANCE.getDeclaracao_Bool();

    /**
     * The meta object literal for the '<em><b>Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__INT = eINSTANCE.getDeclaracao_Int();

    /**
     * The meta object literal for the '<em><b>Zero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__ZERO = eINSTANCE.getDeclaracao_Zero();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.CenaImpl <em>Cena</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.CenaImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getCena()
     * @generated
     */
    EClass CENA = eINSTANCE.getCena();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CENA__NAME = eINSTANCE.getCena_Name();

    /**
     * The meta object literal for the '<em><b>Textos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CENA__TEXTOS = eINSTANCE.getCena_Textos();

    /**
     * The meta object literal for the '<em><b>Imagem</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CENA__IMAGEM = eINSTANCE.getCena_Imagem();

    /**
     * The meta object literal for the '<em><b>Sound</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CENA__SOUND = eINSTANCE.getCena_Sound();

    /**
     * The meta object literal for the '<em><b>Escolhas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CENA__ESCOLHAS = eINSTANCE.getCena_Escolhas();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.ImagemImpl <em>Imagem</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.ImagemImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getImagem()
     * @generated
     */
    EClass IMAGEM = eINSTANCE.getImagem();

    /**
     * The meta object literal for the '<em><b>Caminho</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGEM__CAMINHO = eINSTANCE.getImagem_Caminho();

    /**
     * The meta object literal for the '<em><b>Linha</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGEM__LINHA = eINSTANCE.getImagem_Linha();

    /**
     * The meta object literal for the '<em><b>Coluna</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGEM__COLUNA = eINSTANCE.getImagem_Coluna();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.TextoImpl <em>Texto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.TextoImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getTexto()
     * @generated
     */
    EClass TEXTO = eINSTANCE.getTexto();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXTO__TEXT = eINSTANCE.getTexto_Text();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXTO__VAR = eINSTANCE.getTexto_Var();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.EscolhasImpl <em>Escolhas</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.EscolhasImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getEscolhas()
     * @generated
     */
    EClass ESCOLHAS = eINSTANCE.getEscolhas();

    /**
     * The meta object literal for the '<em><b>Single Choice</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESCOLHAS__SINGLE_CHOICE = eINSTANCE.getEscolhas_SingleChoice();

    /**
     * The meta object literal for the '<em><b>Has If</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESCOLHAS__HAS_IF = eINSTANCE.getEscolhas_HasIf();

    /**
     * The meta object literal for the '<em><b>Expressao If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESCOLHAS__EXPRESSAO_IF = eINSTANCE.getEscolhas_ExpressaoIf();

    /**
     * The meta object literal for the '<em><b>Escolhas IF</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESCOLHAS__ESCOLHAS_IF = eINSTANCE.getEscolhas_EscolhasIF();

    /**
     * The meta object literal for the '<em><b>Has Else</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESCOLHAS__HAS_ELSE = eINSTANCE.getEscolhas_HasElse();

    /**
     * The meta object literal for the '<em><b>Escolhas ELSE</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESCOLHAS__ESCOLHAS_ELSE = eINSTANCE.getEscolhas_EscolhasELSE();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.EscolhaImpl <em>Escolha</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.EscolhaImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getEscolha()
     * @generated
     */
    EClass ESCOLHA = eINSTANCE.getEscolha();

    /**
     * The meta object literal for the '<em><b>Textos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESCOLHA__TEXTOS = eINSTANCE.getEscolha_Textos();

    /**
     * The meta object literal for the '<em><b>Comando</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESCOLHA__COMANDO = eINSTANCE.getEscolha_Comando();

    /**
     * The meta object literal for the '<em><b>If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESCOLHA__IF = eINSTANCE.getEscolha_If();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESCOLHA__ID = eINSTANCE.getEscolha_Id();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.ComandoImpl <em>Comando</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.ComandoImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getComando()
     * @generated
     */
    EClass COMANDO = eINSTANCE.getComando();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO__ID = eINSTANCE.getComando_Id();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.RandomImpl <em>Random</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.RandomImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getRandom()
     * @generated
     */
    EClass RANDOM = eINSTANCE.getRandom();

    /**
     * The meta object literal for the '<em><b>Possibilidades Int</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANDOM__POSSIBILIDADES_INT = eINSTANCE.getRandom_PossibilidadesInt();

    /**
     * The meta object literal for the '<em><b>Possibilidades String</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANDOM__POSSIBILIDADES_STRING = eINSTANCE.getRandom_PossibilidadesString();

    /**
     * The meta object literal for the '<em><b>Possibilidades Bool</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANDOM__POSSIBILIDADES_BOOL = eINSTANCE.getRandom_PossibilidadesBool();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.PlaySoundImpl <em>Play Sound</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.PlaySoundImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getPlaySound()
     * @generated
     */
    EClass PLAY_SOUND = eINSTANCE.getPlaySound();

    /**
     * The meta object literal for the '<em><b>File path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLAY_SOUND__FILE_PATH = eINSTANCE.getPlaySound_File_path();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.IfImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Expressao If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__EXPRESSAO_IF = eINSTANCE.getIf_ExpressaoIf();

    /**
     * The meta object literal for the '<em><b>Id If</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ID_IF = eINSTANCE.getIf_IdIf();

    /**
     * The meta object literal for the '<em><b>Elif</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ELIF = eINSTANCE.getIf_Elif();

    /**
     * The meta object literal for the '<em><b>Id Else</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ID_ELSE = eINSTANCE.getIf_IdElse();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.AtribuicaoImpl <em>Atribuicao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.AtribuicaoImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getAtribuicao()
     * @generated
     */
    EClass ATRIBUICAO = eINSTANCE.getAtribuicao();

    /**
     * The meta object literal for the '<em><b>Expressao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUICAO__EXPRESSAO = eINSTANCE.getAtribuicao_Expressao();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUICAO__STRING = eINSTANCE.getAtribuicao_String();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.ExpressaoImpl <em>Expressao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.ExpressaoImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getExpressao()
     * @generated
     */
    EClass EXPRESSAO = eINSTANCE.getExpressao();

    /**
     * The meta object literal for the '<em><b>Termos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO__TERMOS = eINSTANCE.getExpressao_Termos();

    /**
     * The meta object literal for the '<em><b>Ou</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSAO__OU = eINSTANCE.getExpressao_Ou();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.TermoLogicoImpl <em>Termo Logico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.TermoLogicoImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getTermoLogico()
     * @generated
     */
    EClass TERMO_LOGICO = eINSTANCE.getTermoLogico();

    /**
     * The meta object literal for the '<em><b>Fatores</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_LOGICO__FATORES = eINSTANCE.getTermoLogico_Fatores();

    /**
     * The meta object literal for the '<em><b>E</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERMO_LOGICO__E = eINSTANCE.getTermoLogico_E();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.FatorLogicoImpl <em>Fator Logico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.FatorLogicoImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getFatorLogico()
     * @generated
     */
    EClass FATOR_LOGICO = eINSTANCE.getFatorLogico();

    /**
     * The meta object literal for the '<em><b>Nao</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FATOR_LOGICO__NAO = eINSTANCE.getFatorLogico_Nao();

    /**
     * The meta object literal for the '<em><b>Parcela</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FATOR_LOGICO__PARCELA = eINSTANCE.getFatorLogico_Parcela();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.Parcela_logicaImpl <em>Parcela logica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.Parcela_logicaImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getParcela_logica()
     * @generated
     */
    EClass PARCELA_LOGICA = eINSTANCE.getParcela_logica();

    /**
     * The meta object literal for the '<em><b>P</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARCELA_LOGICA__P = eINSTANCE.getParcela_logica_P();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARCELA_LOGICA__EXP = eINSTANCE.getParcela_logica_Exp();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.ExpressaoRelacionalImpl <em>Expressao Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.ExpressaoRelacionalImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getExpressaoRelacional()
     * @generated
     */
    EClass EXPRESSAO_RELACIONAL = eINSTANCE.getExpressaoRelacional();

    /**
     * The meta object literal for the '<em><b>Expressoes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_RELACIONAL__EXPRESSOES = eINSTANCE.getExpressaoRelacional_Expressoes();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSAO_RELACIONAL__OP = eINSTANCE.getExpressaoRelacional_Op();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.ExpressaoAritmeticaImpl <em>Expressao Aritmetica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.ExpressaoAritmeticaImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getExpressaoAritmetica()
     * @generated
     */
    EClass EXPRESSAO_ARITMETICA = eINSTANCE.getExpressaoAritmetica();

    /**
     * The meta object literal for the '<em><b>Termos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_ARITMETICA__TERMOS = eINSTANCE.getExpressaoAritmetica_Termos();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSAO_ARITMETICA__OP = eINSTANCE.getExpressaoAritmetica_Op();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.TermoImpl <em>Termo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.TermoImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getTermo()
     * @generated
     */
    EClass TERMO = eINSTANCE.getTermo();

    /**
     * The meta object literal for the '<em><b>Fatores</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO__FATORES = eINSTANCE.getTermo_Fatores();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERMO__OP = eINSTANCE.getTermo_Op();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.FatorImpl <em>Fator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.FatorImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getFator()
     * @generated
     */
    EClass FATOR = eINSTANCE.getFator();

    /**
     * The meta object literal for the '<em><b>Parcelas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FATOR__PARCELAS = eINSTANCE.getFator_Parcelas();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FATOR__OP = eINSTANCE.getFator_Op();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.playLang.impl.ParcelaImpl <em>Parcela</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.playLang.impl.ParcelaImpl
     * @see br.ufscar.dc.compiladores.playLang.impl.PlayLangPackageImpl#getParcela()
     * @generated
     */
    EClass PARCELA = eINSTANCE.getParcela();

    /**
     * The meta object literal for the '<em><b>Sub</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARCELA__SUB = eINSTANCE.getParcela_Sub();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARCELA__ID = eINSTANCE.getParcela_Id();

    /**
     * The meta object literal for the '<em><b>Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARCELA__INT = eINSTANCE.getParcela_Int();

  }

} //PlayLangPackage
