/**
 * generated by Xtext 2.23.0
 */
package br.ufscar.dc.compiladores.playLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Texto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Texto#getText <em>Text</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.playLang.Texto#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getTexto()
 * @model
 * @generated
 */
public interface Texto extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getTexto_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Texto#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(Declaracao)
   * @see br.ufscar.dc.compiladores.playLang.PlayLangPackage#getTexto_Var()
   * @model
   * @generated
   */
  Declaracao getVar();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.playLang.Texto#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Declaracao value);

} // Texto
